stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/admin:staging
      pushRemote: true
      registry: harbor.demandcluster.com
    env:
      HOME: /home/jenkins
      KUBECTL_ACTION: replace
      NPM_CONFIG_CACHE: /home/jenkins/.npm
      NPM_USER: demandcluster
      PLUGIN_BUILD_ARGS: gh_token=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
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_TOKEN
    - sourceName: cicd
      sourceKey: GITHUB_TOKEN
timeout: 60
